language: go
addons:
  apt:
    packages:
    - rpm
services:
- docker
after_success:
- test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install: env && go mod download
script: true
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
env:
  global:
  - GO111MODULE=on
  - secure: o5khEZYQG6hAIay0gWReokQXbcQSZI3PZiMbmPSZ13M+4kFukjIElYZ6dEqpSmyx+opDvfsyTSCs4umWuf9BQPpJtrCgMlhwjymtbJOHDyX6rBoVmhDm40n7oYmnhV7uD78vH51/OPq5rK9nnRY5o5mYgX+O9k3XDBIO3SkQHcn89Mumg7dyUYIDoHdWAxN0W82UXTKk9cZI5eZoxzFrHm4D1N0cKv9Qlnb9FmBCtuMZAOOfau9pzDr+7Wb1nhfUtFPZdt2KD6VtJqaayEJiDpSEijyf2P6Una7TvckvCgV9qdNT+7p1Bpowkci45+wogxii7V+uLclOSbBLQjiKxGedE9lm0VPwTViw91QchcJf82dKNixbXdGC2OWRR+DKcs9Yn54c9yxREX/L+Wphzl4umzyW3C1UsibybOCpa3aj+aSC8Y5mBeF5bVHA/x7R/s0sUxUBVzUfK8T9eF/2Spu+PIvhD2Tut7uUN5yQEdR3zM5QawD8YDiCVs6pcbOGoMnqjdQ2ON5t5g1n9XIsawreWQ5pwVt0I7AXYOmsw4MPN7/wKt9GoNkmKZELiKoszVNdu22aA2pYEh8O18c6r5aXjNOCvgXZnAZAjZzoGGdEY0vQ78vdpp2wBxvk6RP0+ei7dyQk4LpHcX2120Pjz6HDhV+2fKoTTQLcc+Gzlm8=
  - secure: wjmnAgaKP8jG74f4bOqfQlU8KPsr0VXu37Sx5LZSlY33Qql1pDnme0GQVoZox5UxthL4fSdH4X+VSlRNIGIA8cbRN64/0RVlcD3UuS837Zvu0gPKg4EIeuzHPzibhd9yEaF3uy4oeWCJ2l0RIW8nhW92bsQ/9aKxRPoojR7JfU8vlcIEaDf2CwxPOGK/jSGeaIA2dfey1rJeLic2LMpUog1FINl2S7oKaZGyLkbEhsgsKak6LBHJEZBK0MvWtizKddQo3Z1zY/nIPXXGPrnYQH1LNo/GadUfWDbsaxlQt5j1XR7ohUzCg1dBq3mVwoO+U8coZhm4Gzw1zuIxS8mgCAF+2cvzy1AuWKuPEB6TpeHytkqO1xIuGCn9x9QB+Fw1FX32HJvJaa2QFhAEpyaBy9heAIyGJYkTMRblLeqOguz/oYpgHxweFzaHieiipx9i32927mc8AfqKvYfeDqJaXqF3naQSPupoc4t+qFFeuLgUObCUUMccUgzRkd57pfHhpfaYt+fVTWE6n6KXJRRmLnsVtSbjDqG9XMHpnDAE9pegiJ1d4EbNbsToNbRXdftuHDpNZda56XDyN0vp4bSWbhBGiuuByMYZPFdHVivvs53OmTXwYRqch3mEgi/UUG3S6wrxv4WmUi3zD6gmmLC6jQmOD5LA1INY4uLpYT9hooo=
  matrix:
    secure: 3kGJqs9SQF3cKtqezjWxnEIWmbfgTNXBa55eHs+bcMnlmPOjwrbH+whhuiajJ1n6a/YQzpbjp+v6LrBYeObg4nd5dWDkkBjALzab+ziR/kWcsCKhLJ5G9VNc/BV50vpbord+7RfeFACSZGUEzed0a9mRxP/QCpgVeNh6QKOTcp0LF/Zv/+0CdcB7CB/rvWzI+XqvL7JsejfvXKQjin2UmH8GNE98xPM6x/rmfjaQd4p3WwlyBVGEDbPuQno66fu8XpQ76lGvhUaRpLzPyd45Kl7hJJw41NZ4g0uDLfjao9BuVCx1dILmSheaZL60oN1uqa1v6Yv+d817/4cNM7Bp3FnR1BgtqR93EhYdTuZUDjV3k1WDDU0+fMBDljQLDMAeeTJwzF1Ug9F56wkBG41ICq8GAfwmlhYr3PradgmzK9Uw2MVBluGn0wtpN6Y2CPOroWW2efZOZOFJM27K32Gep7Laa/XNIbsfTDENjuPrBoA4Dzv1GXFzPkz0jlUi+PHRlbBxreHVutPvjWS2bXOCb1dvCa/+ektT9pvh1xlsrKJQPfA9Rrft05rQBf4lCLSB+zpLfxZh2NrwETllYwZ6Qer4uzNmp2BuPdmODRN4/eKg0crPLkdM1A2lbX8CyaFJxHTGM4lpj99+tAXebjDHp5dP8LQgQ8Ojh0EogrUlnCg=
